const NYCategories = {
  Arts: "Arts",
  Automobiles: "Automobiles",
  Autos: "Autos",
  Blogs: "Blogs",
  Books: "Books",
  Booming: "Booming",
  Business: "Business",
  BusinessDay: "Business Day",
  Corrections: "Corrections",
  CrosswordsAndGames: "Crosswords & Games",
  DiningAndWine: "Dining & Wine",
  EditorsNotes: "Editors' Notes",
  Education: "Education",
  FashionAndStyle: "Fashion & Style",
  Food: "Food",
  FrontPage: "Front Page",
  Giving: "Giving",
  GlobalHome: "Global Home",
  GreatHomesAndDestinations: "Great Homes & Destinations",
  Health: "Health",
  HomeAndGarden: "Home & Garden",
  InternationalHome: "International Home",
  JobMarket: "Job Market",
  Learning: "Learning",
  Magazine: "Magazine",
  Movies: "Movies",
  Multimedia: "Multimedia",
};

export default NYCategories;
